version: "3.4"
services:
  db:
    container_name: pycon-2019-demo-db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=mydbuser
      - POSTGRES_PASSWORD=mydbpassword
      - TZ=Asia/Jakarta
      - PGTZ=Asia/Jakarta
    ports:
      - "5432:5432"
    # networks :
    #   - default
    # volumes:
    #   - ./mvp/src/juloserver/setup_database.sql:/docker-entrypoint-initdb.d

# networks:
#   default:
#     driver: bridge

# volumes:
#   logvolume01: {}
