version: "3.4"
services:
  db:
    container_name: pycon-2019-demo-db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=mydbuser
      - POSTGRES_PASSWORD=mydbpassword
      - TZ=Asia/Jakarta
      - PGTZ=Asia/Jakarta
    tmpfs:
      - /var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
